### ISSUE TITLE
save findings to the database

### ISSUE THREAD

**Issue by pman05** [KewTeacher/UprootingInvaders#25]

**Comment by lanoflatfaceo** [comment]
Worked on making it possible to get data from plantid.html to view.py

**Comment by lanoflatfaceo** [comment]
Worked on this for about 40 minutes. It should technically be able to save the findings to the database. However, I do not have access to the DB since it is technically Cairo's. Thus, additional work will need to be done in class in order to configure what needs to go where on MongoDB.

**Comment by KewTeacher** [comment]
to view the data base: Download Mongo Compass: https://www.mongodb.com/try/download/compass
unzip it, then paste in the connection string from .env

**Comment by KewTeacher** [comment]
![image](https://user-images.githubusercontent.com/31484449/168325710-90d9e7d8-4a61-481a-b60c-94db780b4e7e.png)

**Comment by KewTeacher** [comment]
Or look at this:
![image](https://user-images.githubusercontent.com/31484449/168326336-b6186454-6e42-4617-a64b-8569836a3e66.png)
