### ISSUE TITLE
After submitting a finding, save to db and redirect to map

### ISSUE THREAD

**Issue by KewTeacher** [KewTeacher/UprootingInvaders#31]

**Comment by lanoflatfaceo** [comment]
spent 35 minutes on the issue. It seems that the send data is undefined when trying to run it. There was originally a syntax problem previously, but that problem was fixed.

**Comment by lanoflatfaceo** [comment]
Iarf

**Comment by KewTeacher** [comment]
saving finding but not redirecting

**Comment by KewTeacher** [comment]
redirects
