### ISSUE TITLE
Plant API

### ISSUE THREAD

**Issue by pman05** [KewTeacher/UprootingInvaders#6]
https://web.plant.id/plant-identification-api/
https://plantidentifier.info/
https://www.programmableweb.com/api/plantid

**Comment by KewTeacher** [comment]
Some of these you can test on the website. Try each one out if possible, and write up a short summary for each. Is there one that you recommend over the others?

**Comment by pman05** [comment]
plant.id is the best one. There will be a fee if we want to make it a public app for everybody to use.
plant identifier is an app
the third option is the same as the first one. I thought it was something different when I first put it in.

**Comment by KewTeacher** [comment]
Paul, check this one out and let me know what you think: https://my.plantnet.org/

**Comment by KewTeacher** [comment]
user: daronson@kewforest.org
pass: Comp$c!1

**Comment by Jamestvvo** [comment]
2b10FP9NjPISdGPyjNBrQowG
